
[env]
platform = ststm32
framework = cmsis

#lib_deps = cli
#	printf

build_flags = 
	-D USE_DEBUG=1
	-D STM32
	-D ARCH_STM32
	-D FREERTOS=1
	-I lib
    -I include
    -I include/ARM_CM4F
    -Wno-missing-field-initializers
    '-Wformat=2'
    '-Werror=format'
    '-Wno-format-zero-length'
    '-Wno-format-nonliteral'
    -D CLI_MAX_ARGS=20
    -L third_party/build
    -l rtos.a

lib_deps = printf

#extra_scripts = pre:link_libs.py, fix_fpu.py, scons_build.py
extra_scripts = pre:link_libs.py, pre:fix_fpu.py, scons_build.py

;
;

[env:nucleo_f446re]
board = nucleo_f446re

board_build.mcu = stm32f446ret6

board_build.f_cpu = 180000000L

#board_build.cmsis.fpu = fpv4-sp-d16
#board_build.cmsis.fpu_abi = softfp

upload_protocol = stlink

build_flags = ${env.build_flags} 
    -mcpu=cortex-m4
    -mthumb
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16
    -D ARMMATH_CM4

#   FIN
