
[env]
platform = ststm32
;framework = cmsis
framework = stm32cube

build_flags = 
    -g
    -D USE_DEBUG=1
    -D STM32
    -D ARCH_STM32
    -D FREERTOS=1
    -I lib
    -Wno-missing-field-initializers
    '-Wformat=2'
    '-Werror=format'
    '-Wno-format-zero-length'
    '-Wno-format-nonliteral'
    -D CLI_MAX_ARGS=20
    -I ${PROJECT_DIR}/include/
    -I ${PROJECT_DIR}/third_party/freertos/include/
    -I ${PROJECT_DIR}/include/ARM_CM4F/
    -I ${PROJECT_DIR}/test
    -D USE_FREERTOS_MALLOC
    -L third_party/build
    -l rtos.a
    -Wl,--whole-archive
    -l test.a
    -Wl,--no-whole-archive
    -Wl,--wrap,malloc
    -Wl,--wrap,_malloc_r
    -Wl,--wrap,nano_malloc
    -Wl,--wrap,free
    -Wl,--wrap,nano_free
    -Wl,--wrap,realloc
    -Wl,-Map=output.map
    -Wl,--undefined=force_test_thread

;    -mthumb-interwork

lib_deps = printf
    cli
    fatfs

extra_scripts = pre:link_libs.py, pre:fix_fpu.py, scons_build.py

;
;

[env:nucleo_f446re]
board = nucleo_f446re

board_build.mcu = stm32f446ret6
board_build.f_cpu = 180000000L

upload_protocol = stlink

build_flags = ${env.build_flags} 
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16
    -D ARMMATH_CM4
    ;-mcpu=cortex-m4
    ;-mthumb

#   FIN
